In [1]:
import numpy as np

In [2]:
A = np.random.rand(5,5)
A

array([[ 0.80255005,  0.87597821,  0.01519759,  0.56811812,  0.50387048],
       [ 0.80706928,  0.30342462,  0.58599469,  0.67366389,  0.96014838],
       [ 0.84062361,  0.04682348,  0.71840468,  0.03374765,  0.73038484],
       [ 0.85121945,  0.79998396,  0.24021516,  0.37803951,  0.03734695],
       [ 0.72253756,  0.53902596,  0.45865731,  0.87380274,  0.21125889]])

In [3]:
for i in range (0,5):
    for j in range (0,5):
        A[i,j] = 10*i + j

In [4]:
A

array([[  0.,   1.,   2.,   3.,   4.],
       [ 10.,  11.,  12.,  13.,  14.],
       [ 20.,  21.,  22.,  23.,  24.],
       [ 30.,  31.,  32.,  33.,  34.],
       [ 40.,  41.,  42.,  43.,  44.]])

In [5]:
A[1,2]

12.0

In [6]:
A[1][2]

12.0

In [8]:
A[1:2]

array([[ 10.,  11.,  12.,  13.,  14.]])

In [9]:
A[2:1]

array([], shape=(0, 5), dtype=float64)

In [10]:
A[1 2]

SyntaxError: invalid syntax (<ipython-input-10-12307bdafcf1>, line 1)