In [1]:
import numpy as np

In [3]:
A = np.array([[1,0,2],[2,1,5],[3,2,8]])

In [6]:
B = np.eye(3)

In [7]:
B

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [8]:
C = B.dot(A)

In [9]:
C

array([[ 1.,  0.,  2.],
       [ 2.,  1.,  5.],
       [ 3.,  2.,  8.]])

In [10]:
A

array([[1, 0, 2],
       [2, 1, 5],
       [3, 2, 8]])

In [11]:
type (C)

numpy.ndarray

In [12]:
A = A + 0.5

In [13]:
A

array([[ 1.5,  0.5,  2.5],
       [ 2.5,  1.5,  5.5],
       [ 3.5,  2.5,  8.5]])

In [14]:
D = A - C

In [15]:
D

array([[ 0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5],
       [ 0.5,  0.5,  0.5]])

In [16]:
A

array([[ 1.5,  0.5,  2.5],
       [ 2.5,  1.5,  5.5],
       [ 3.5,  2.5,  8.5]])

In [17]:
B

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [18]:
C

array([[ 1.,  0.,  2.],
       [ 2.,  1.,  5.],
       [ 3.,  2.,  8.]])

In [19]:
C = C.T

In [20]:
C

array([[ 1.,  2.,  3.],
       [ 0.,  1.,  2.],
       [ 2.,  5.,  8.]])

In [24]:
detA = np.linalg.det(A)

In [25]:
detA

-1.7763568394002524e-15

In [26]:
A

array([[ 1.5,  0.5,  2.5],
       [ 2.5,  1.5,  5.5],
       [ 3.5,  2.5,  8.5]])

In [27]:
C

array([[ 1.,  2.,  3.],
       [ 0.,  1.,  2.],
       [ 2.,  5.,  8.]])

In [28]:
detC = np.linalg.det(C)

In [29]:
C

array([[ 1.,  2.,  3.],
       [ 0.,  1.,  2.],
       [ 2.,  5.,  8.]])

In [30]:
detC

0.0

In [31]:
rgA = np.linalg.matrix_rank(A)
rgA

2

In [32]:
rgC = np.linalg.matrix_rank(C)

In [33]:
rgC

2

In [36]:
Am = np.linalg.inv(A)

In [37]:
Am

array([[  5.62949953e+14,  -1.12589991e+15,   5.62949953e+14],
       [  1.12589991e+15,  -2.25179981e+15,   1.12589991e+15],
       [ -5.62949953e+14,   1.12589991e+15,  -5.62949953e+14]])

In [38]:
Ia = A.dot(Am)
Ib = Am.dot(A)

In [39]:
Ia

array([[ 1. ,  0. ,  0. ],
       [ 0.5,  0. ,  0. ],
       [ 0. ,  0. ,  1. ]])

In [40]:
Ib

array([[ 0.5 , -0.25, -1.  ],
       [-1.  ,  1.  ,  0.  ],
       [ 0.5 ,  0.  ,  0.  ]])

In [41]:
A

array([[ 1.5,  0.5,  2.5],
       [ 2.5,  1.5,  5.5],
       [ 3.5,  2.5,  8.5]])

In [43]:
Cm = np.linalg.inv(C)
Cm

LinAlgError: Singular matrix

In [44]:
C

array([[ 1.,  2.,  3.],
       [ 0.,  1.,  2.],
       [ 2.,  5.,  8.]])

In [45]:
C.det

AttributeError: 'numpy.ndarray' object has no attribute 'det'

In [46]:
np.det(C)

AttributeError: 'module' object has no attribute 'det'

In [47]:
np.linalg.det(C)

0.0

In [48]:
w, v = np.linalg.eig(A)

In [49]:
w

array([  1.11409647e+01,   3.59035337e-01,  -3.85199788e-16])

In [50]:
v

array([[ 0.2388115 ,  0.87141341, -0.40824829],
       [ 0.52716401,  0.21532393, -0.81649658],
       [ 0.81551651, -0.44076555,  0.40824829]])

In [51]:
A = np.array([[1,1],[1,2]])

In [52]:
A

array([[1, 1],
       [1, 2]])

In [53]:
Ia = A.dot(A.T)

In [54]:
Ia

array([[2, 3],
       [3, 5]])

In [55]:
A.T

array([[1, 1],
       [1, 2]])

In [56]:
e = np.arange(1, 13, 2).reshape((3, 2))

In [57]:
e

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [58]:
d = np.ones((10, 10))

In [59]:
d

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

In [63]:
b = np.eye((2, 3))

TypeError: an integer is required

In [61]:
b

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.]])

In [66]:
a = np.eye(4, 5)
b = a[[0, 3], [1, 3]]

In [65]:
a

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.]])

In [67]:
b
type(b)

numpy.ndarray

In [68]:
b

array([ 0.,  1.])

In [69]:
b.shape

(2,)

In [71]:
b = np.det(a)

AttributeError: 'module' object has no attribute 'det'